services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_homolog:/data/db
    networks:
      - backend_homolog

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./back/.env
    depends_on:
      - mongo
    networks:
      - backend_homolog

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - backend_homolog

volumes:
  mongodb_data_homolog:

networks:
  backend_homolog:
