services:
  mongo:
    container_name: mongo_tarefas_prod
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_prod:/data/db
    networks:
      - backend_prod

  api:
    container_name: api_tarefas_prod
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env
    depends_on:
      - mongo
    networks:
      - backend_prod

  front:
    container_name: front_tarefas_prod
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend_prod

volumes:
  mongodb_data_prod:

networks:
  backend_prod:
