services:
  mongo:
    image: mongo
    container_name: mongo_tarefas
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  api:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: api_tarefas
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./back/.env
    depends_on:
      - mongo
    networks:
      - backend

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front_tarefas
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
