version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db_data:/data/db
    networks:
      - backend

  api:
    build: 
      context: ./back
      dockerfile: Dockerfile
    expose:
      - "3000"
    restart: always
    depends_on:
      - mongo
    networks:
      - backend

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - api
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
