services:
  mongo:
    image: mongo
    container_name: mongo_tarefas
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_tarefas
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017/tarefasdb
      PORT: 3000
    depends_on:
      - mongo
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend: