name: CI/CD - Deploy Homolog

on:
  push:
    branches: [homolog]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy na VM (homolog)
        run: |
          DEPLOY_PATH=${{ secrets.DEPLOY_PATH }}
          HOMOLOG_BRANCH=${{ secrets.HOMOLOG_BRANCH }}

          ssh -p 2222 -v -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e
            cd $DEPLOY_PATH

            # Garante que estamos na branch certa
            git fetch origin
            git checkout $HOMOLOG_BRANCH
            git reset --hard origin/$HOMOLOG_BRANCH
            git pull

            sudo docker compose -f docker-compose.homolog.yaml up -d --build
          EOF
