name: Deploy Production

on:
  workflow_dispatch:  # acionado manualmente

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Promover Homologação → Produção
        run: |
          DEPLOY_PATH=${{ secrets.DEPLOY_PATH }}
          PROMOTE_PATH=${{ secrets.PROMOTE_PATH }}
          PRODUCTION_BRANCH=${{ secrets.PRODUCTION_BRANCH }}

          ssh -p 2222 -v -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e

            echo "🚀 Copiando front e back"
            rsync -av --exclude='node_modules' $DEPLOY_PATH/front $PROMOTE_PATH/
            rsync -av --exclude='node_modules' $DEPLOY_PATH/back $PROMOTE_PATH/

            echo "📄 Copiando docker-compose.production.yaml"
            rsync -av $DEPLOY_PATH/docker-compose.production.yaml $PROMOTE_PATH/

            echo "📦 Executando compose de produção"
            cd $PROMOTE_PATH
            docker compose -f docker-compose.production.yaml up -d --build

            docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Image}}"
          EOF

